<?php

namespace AwesomeCoder\Support\Facades;

/**
 * @method static \AwesomeCoder\Database\Connection connection(string|null $name = null)
 * @method static void registerDoctrineType(string $class, string $name, string $type)
 * @method static void purge(string|null $name = null)
 * @method static void disconnect(string|null $name = null)
 * @method static \AwesomeCoder\Database\Connection reconnect(string|null $name = null)
 * @method static mixed usingConnection(string $name, callable $callback)
 * @method static string getDefaultConnection()
 * @method static void setDefaultConnection(string $name)
 * @method static string[] supportedDrivers()
 * @method static string[] availableDrivers()
 * @method static void extend(string $name, callable $resolver)
 * @method static void forgetExtension(string $name)
 * @method static array getConnections()
 * @method static void setReconnector(callable $reconnector)
 * @method static \AwesomeCoder\Database\DatabaseManager setApplication(\AwesomeCoder\Contracts\Foundation\Application $plugin)
 * @method static void macro(string $name, object|callable $macro)
 * @method static void mixin(object $mixin, bool $replace = true)
 * @method static bool hasMacro(string $name)
 * @method static void flushMacros()
 * @method static mixed macroCall(string $method, array $parameters)
 * @method static void useDefaultQueryGrammar()
 * @method static void useDefaultSchemaGrammar()
 * @method static void useDefaultPostProcessor()
 * @method static \AwesomeCoder\Database\Schema\Builder getSchemaBuilder()
 * @method static \AwesomeCoder\Database\Query\Builder table(\Closure|\AwesomeCoder\Database\Query\Builder|string $table, string|null $as = null)
 * @method static \AwesomeCoder\Database\Query\Builder query()
 * @method static mixed selectOne(string $query, array $bindings = [], bool $useReadPdo = true)
 * @method static mixed scalar(string $query, array $bindings = [], bool $useReadPdo = true)
 * @method static array selectFromWriteConnection(string $query, array $bindings = [])
 * @method static array select(string $query, array $bindings = [], bool $useReadPdo = true)
 * @method static \Generator cursor(string $query, array $bindings = [], bool $useReadPdo = true)
 * @method static bool insert(string $query, array $bindings = [])
 * @method static int update(string $query, array $bindings = [])
 * @method static int delete(string $query, array $bindings = [])
 * @method static bool statement(string $query, array $bindings = [])
 * @method static int affectingStatement(string $query, array $bindings = [])
 * @method static bool unprepared(string $query)
 * @method static array pretend(\Closure $callback)
 * @method static void bindValues(\PDOStatement $statement, array $bindings)
 * @method static array prepareBindings(array $bindings)
 * @method static void logQuery(string $query, array $bindings, float|null $time = null)
 * @method static void whenQueryingForLongerThan(\DateTimeInterface|\Carbon\CarbonInterval|float|int $threshold, callable $handler)
 * @method static void allowQueryDurationHandlersToRunAgain()
 * @method static float totalQueryDuration()
 * @method static void resetTotalQueryDuration()
 * @method static \AwesomeCoder\Database\Connection beforeExecuting(\Closure $callback)
 * @method static void listen(\Closure $callback)
 * @method static \AwesomeCoder\Database\Query\Expression raw(mixed $value)
 * @method static bool hasModifiedRecords()
 * @method static void recordsHaveBeenModified(bool $value = true)
 * @method static \AwesomeCoder\Database\Connection setRecordModificationState(bool $value)
 * @method static void forgetRecordModificationState()
 * @method static \AwesomeCoder\Database\Connection useWriteConnectionWhenReading(bool $value = true)
 * @method static bool isDoctrineAvailable()
 * @method static bool usingNativeSchemaOperations()
 * @method static \Doctrine\DBAL\Schema\Column getDoctrineColumn(string $table, string $column)
 * @method static \Doctrine\DBAL\Schema\AbstractSchemaManager getDoctrineSchemaManager()
 * @method static \Doctrine\DBAL\Connection getDoctrineConnection()
 * @method static \PDO getPdo()
 * @method static \PDO|\Closure|null getRawPdo()
 * @method static \PDO getReadPdo()
 * @method static \PDO|\Closure|null getRawReadPdo()
 * @method static \AwesomeCoder\Database\Connection setPdo(\PDO|\Closure|null $pdo)
 * @method static \AwesomeCoder\Database\Connection setReadPdo(\PDO|\Closure|null $pdo)
 * @method static string|null getName()
 * @method static string|null getNameWithReadWriteType()
 * @method static mixed getConfig(string|null $option = null)
 * @method static string getDriverName()
 * @method static \AwesomeCoder\Database\Query\Grammars\Grammar getQueryGrammar()
 * @method static \AwesomeCoder\Database\Connection setQueryGrammar(\AwesomeCoder\Database\Query\Grammars\Grammar $grammar)
 * @method static \AwesomeCoder\Database\Schema\Grammars\Grammar getSchemaGrammar()
 * @method static \AwesomeCoder\Database\Connection setSchemaGrammar(\AwesomeCoder\Database\Schema\Grammars\Grammar $grammar)
 * @method static \AwesomeCoder\Database\Query\Processors\Processor getPostProcessor()
 * @method static \AwesomeCoder\Database\Connection setPostProcessor(\AwesomeCoder\Database\Query\Processors\Processor $processor)
 * @method static \AwesomeCoder\Contracts\Events\Dispatcher getEventDispatcher()
 * @method static \AwesomeCoder\Database\Connection setEventDispatcher(\AwesomeCoder\Contracts\Events\Dispatcher $events)
 * @method static void unsetEventDispatcher()
 * @method static \AwesomeCoder\Database\Connection setTransactionManager(\AwesomeCoder\Database\DatabaseTransactionsManager $manager)
 * @method static void unsetTransactionManager()
 * @method static bool pretending()
 * @method static array getQueryLog()
 * @method static void flushQueryLog()
 * @method static void enableQueryLog()
 * @method static void disableQueryLog()
 * @method static bool logging()
 * @method static string getDatabaseName()
 * @method static \AwesomeCoder\Database\Connection setDatabaseName(string $database)
 * @method static \AwesomeCoder\Database\Connection setReadWriteType(string|null $readWriteType)
 * @method static string getTablePrefix()
 * @method static \AwesomeCoder\Database\Connection setTablePrefix(string $prefix)
 * @method static \AwesomeCoder\Database\Grammar withTablePrefix(\AwesomeCoder\Database\Grammar $grammar)
 * @method static void resolverFor(string $driver, \Closure $callback)
 * @method static mixed getResolver(string $driver)
 * @method static mixed transaction(\Closure $callback, int $attempts = 1)
 * @method static void beginTransaction()
 * @method static void commit()
 * @method static void rollBack(int|null $toLevel = null)
 * @method static int transactionLevel()
 * @method static void afterCommit(callable $callback)
 *
 * @see \AwesomeCoder\Database\DatabaseManager
 */
class DB extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'db';
    }
}
